### ISSUE TITLE
Office Online SSO

### ISSUE THREAD

**Issue by saskodh** [OfficeDev/Office-Add-in-NodeJS-SSO#7] opened 2018-02-03 23:39 UTC
Hi, I'm successfully running the completed project locally in Excel on Windows. By following the guide carefully I understood that the SSO should work also on Excel Online. However when I try to run in it there I get the following error:
![Office Online SSO Error](https://tjenaa.bn1301.livefilestore.com/y4mMrHauO5ugCpbzM-iLyl8XWK7Qy1-iwgdslmwkTXXcCmnNw6rjnnVZ_emCJZ5biVeGv9CfhC_Vh1yQ8TJYpBspnr9y8DmYZcTUqsqDz-pm2holsG9tg6AdMPYuqFN-mwOM6WSDbQbtwOKpms_Gl1vERZHXk6Y2OpNpn7RNQmy80IFH1HjrD6mT2gZaJOmXnaENpF65hLlglgF_E2knFkxmA?width=1362&height=658&cropmode=none)
I can't figure it out what is exactly the problem and where these reply urls can be configured.
I'm developing an add-in locally and I would like to be able to run it on Excel Online since it would be easier for debugging.

**Comment by Rick-Kirkham** [comment] 2018-02-04 23:18
Do you get this error when you sideload the add-in or when you open the task pane or when you click the button inside the task pane? Please give the steps that lead up to the error.
Also, are you hosting the add-in on localhost when you try to run it on Office Online?

**Comment by saskodh** [comment] 2018-02-11 18:19
Hi @Rick-Kirkham, sorry for the missing information.
I was running the 'Completed' example on localhost. Loaded the add-in on the side in Office Online by uploading the add-in manifest and trying to list the OneDrive files by clicking on the 'Get My Files from OneDrive' button in the add-in. Once I click the button I get redirected to the page from the screenshot. This same scenario works though when the add-in is sideloaded in Office on Windows.

**Comment by Rick-Kirkham** [comment] 2018-02-26 19:32
We are still working on this.

**Comment by Rick-Kirkham** [comment] 2018-03-09 23:33
The product team has identified a couple of bugs that are behind this. A fix won't be in production for a couple of weeks.

**Comment by Rick-Kirkham** [comment] 2018-11-29 23:32
@saskodh Is this still an issue? If not, I will close this.

**Comment by plamenxpenchev** [comment] 2019-06-17 05:34
Hello, @Rick-Kirkham. I am hitting the exact same issue with the preview (beta) version of the Office API  in Word Online (vain attempts were also made against the latest versions of the `@microsoft/office-js` package). The following occurs when invoking `Office.context.auth.getAccessTokenAsync`:

![office-online-reply-url-err](https://user-images.githubusercontent.com/36263058/59579919-c50f6680-90d7-11e9-984d-9edde4496a7b.png)

- All the steps detailed in https://docs.microsoft.com/en-us/office/dev/add-ins/develop/register-sso-add-in-aad-v2 were thoroughly followed.
- All the suggestions, stemming from a similar issue https://github.com/OfficeDev/Office-Add-in-ASPNET-SSO/issues/23 were also thoroughly followed, namely:
- Making an exact match between **add-in manifest scopes** & **Azure app permissions**.
- All requested permissions have been **consented to**.
- **Sideloading** the addin manifest, instead of uploading it via Sharepoint's Apps for Office (_the same issue is encountered_).
- As you have previously pointed out, `57fb890c-0dab-4253-a5e0-7188c88b2bb4` is the ID for Office Online, or as displayed in the Azure Portal (under Enterprise Applications): **SharePoint Online Client**. Obviously, this application is outside of my control to add reply urls.

Your quick response regarding this matter will be highly appreciated.

**Comment by Rick-Kirkham** [comment] 2019-06-17 18:18
Seems to be a regression bug. I'm going to try to move this to the office-js repo.

**Comment by Rick-Kirkham** [comment] 2019-06-17 18:23
@plamenxpenchev 
The GitHub UI is not listing `office-js` on the list of repos that I can transfer to. Can I ask you to create an [issue on that repo](https://github.com/OfficeDev/office-js/issues)? Then I can assign it to the appropriate person.

**Comment by plamenxpenchev** [comment] 2019-06-18 06:34
@Rick-Kirkham 
Thank you for the quick response! Here is the newly-opened issue https://github.com/OfficeDev/office-js/issues/563

**Comment by Rick-Kirkham** [comment] 2019-06-18 09:03
The issue is now being tracked in another repo and it isn't really an issue for this sample, _per se_. So I'm closing this.

**Closed as completed by Rick-Kirkham** 2019-06-18 09:03 UTC
